### ISSUE TITLE
Colorpicker: invalid option 's'

### ISSUE THREAD

**Issue by Waiifu** [sdushantha/farge#11]
The input arguments of colorpicker were changed as of 3 hours ago. Short / s is no longer valid.

https://github.com/ym1234/colorpicker/commit/419958fc9c81c669ddc153ae5658e6ce198ae335

**Comment by sdushantha** [comment]
@Waiifu Well I guess that good Because that means I can remove the convertion from hex to rgb in farge.

EDIT: Actually no, I am not going to remove the convertion function because the current method we use for farge to work in Wayland needs the function. So I can just update the flag.

**Comment by sdushantha** [comment]
I fixed this :)
