### ISSUE TITLE
[Usability] Show 'press q to exit image window' on the first use

### ISSUE THREAD

**Issue by CRImier** [sdushantha/farge#12]
Following the "usability of `farge`" discussion on Reddit, I suggest that, the first time you call `farge`, it outputs something like `To close the color window, click on it and press 'q'` on the command-line. Since the tool is command-line, this should be a good way to make it more intuitively-usable while still keeping it nice-looking! As for the internals - you could probably just put a flag file in one of the XDG-approved directories (i.e. .config), check for it and no longer show the message once it's been shown once.

**Comment by sdushantha** [comment]
I fixed this :)

**Comment by CRImier** [comment]
thank you!
