### ISSUE TITLE
Could you please make a release for this project?

### ISSUE THREAD

**Issue by kedodrill** [sdushantha/farge#13]
Hi there,

I am wanting to build and maintain this package for Solus Linux. It would greatly benefit me (and possibly others, if the build system works similarly) if you could make a release with a .tar, since the builder scripts need that. I'd really appreciate it!

**Comment by sdushantha** [comment]
Hey @kedodrill :)

This is the first time I have ever made a release, so if I did something wrong, please let me know so I can fix it :+1:

**Comment by kedodrill** [comment]
@sdushantha Thanks so much! Everything looks right to me...I'll package it up on Solus either tonight or sometime next week and report back here with the result.

**Comment by sdushantha** [comment]
Once you have packaged it, feel free to make a PR to the README so that people can know that they can install `farge` from there too :)
