### ISSUE TITLE
Add `xcolor` to dependencies

### ISSUE THREAD

**Issue by Bad3r** [sdushantha/farge#25]
Hi

I just installed the package from the AUR and when I ran it I received an error informing me that I need to install the dependency `xcolor`. This is not mentioned in the readme I thought you might want to add it.

**Comment by Ziad0dev** [comment]
`xcolor` dependency is mentioned for x11 users on the readme

**Comment by Bad3r** [comment]
My bad didn't notice it. Will close the issue. Thank you for the awesome tool and quick response!
