### ISSUE TITLE
bc as dependency

### ISSUE THREAD

**Issue by davidbgonz** [sdushantha/farge#28]
Installed farge though AUR on i3wm. 

This is the default output without bc (same result with any arg):
```
➜  ~ farge                   
/usr/bin/farge: line 104: bc: command not found
/usr/bin/farge: line 104: [: : integer expression expected
```

With bc the error is not present anymore. Without bc the command is working as expected though so I am not sure what exactly how it is being used.

**Comment by jtbx** [comment]
Fixed with #31
