### ISSUE TITLE
Add option to output color via pipe or stdout for use in scripts

### ISSUE THREAD

**Issue by thejml** [sdushantha/farge#3]
I’d love to be able to output color codes via pipe or stdout to record outputs, set environment variables, etc.

**Comment by bool3max** [comment]
`farge` relies on an external tool to actually pick the color,  `colorpicker`. It's invoked by `farge` with the `-soq` flags. 

Implementing this doesn't seem to be necessary, just use `colorpicker`.

**Comment by sdushantha** [comment]
@thejml fixed this :)
