### ISSUE TITLE
Gdk-CRITICAL errors

### ISSUE THREAD

**Issue by Waiifu** [sdushantha/farge#4]
I'm running KDE on Arch 5.2.1, and I'm getting
```
(colorpicker:24892): Gdk-CRITICAL **: 06:45:25.595: IA__gdk_screen_get_root_window: assertion 'GDK_IS_SCREEN (screen)' failed

(colorpicker:24892): Gdk-CRITICAL **: 06:45:25.595: IA__gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed

(colorpicker:24892): Gdk-CRITICAL **: 06:45:25.595: IA__gdk_pointer_grab: assertion 'window != NULL' failed
```

no matter what.

**Comment by sdushantha** [comment]
@Waiifu Are you using X11 or Wayland?

By the way, this is not an issue with `farge` but it is an issue with `colorpicker`. So it would be best to open an issue in this repo: https://github.com/ym1234/colorpicker

**Comment by Siphonay** [comment]
If you installed farge from my AUR package, you probably got colorpicker from the AUR too. I forgot to check but I just noticed that it's using a very outdated fork of colorpicker. I'll look into taking ownership of the package and updating it, or make a colorpicker-git package and see if I can make farge-git use this one instead

**Comment by Waiifu** [comment]
@sdushantha X11. Oh, right. And yeah It's probably because of the out-dated color-picker dependency from @Siphonay 's AUR package. Should be easy enough to fix from here on out, cheers.
